export const INCORRECT_PASS = "INCORRECT_PASS";
export const PASS_FIELDS_DONT_MATCH = "PASS_FIELDS_DONT_MATCH";
export const OCCUPIED_LOGIN = "OCCUPIED_LOGIN";
export const OCCUPIED_EMAIL = "OCCUPIED_EMAIL";
export const ONE_FIELD_EMPTY = "ONE_FIELD_EMPTY";
export const ALREADY_IN_REG_PROCCESS = "ALREADY_IN_REG_PROCCESS";
export const SERVER_ERROR = "SERVER_ERROR";